name: Test Flutter Build (No Nix)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.29.1

      - name: Configure Flutter environment for Linux
        run: |
          flutter doctor -v

      - name: Install Linux Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev libstdc++-12-dev

      - name: Build for Linux
        run: |
          cd app
          flutter build linux

      - name: Build Android APK
        run: |
          cd app
          flutter build apk --split-per-abi  # Splits APKs per ABI for smaller download sizes

      - name: Upload Linux Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-build
          path: app/build/linux/x64/release/bundle

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: apk-build
          path: app/build/app/outputs/flutter-apk/app-release.apk
